version: '3.8'

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile 
      args: 
        VARIANT: "bullseye"
        PHP_VERSION: "7.4"
        # WP_PLUGINS:
        #   https://downloads.wordpress.org/plugin/gutenberg.11.9.1.zip
        #   https://downloads.wordpress.org/plugin/theme-check.20210921.zip
        #   https://downloads.wordpress.org/plugin/query-monitor.3.7.1.zip
    # depends_on: ['db']
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends. 
    command: sleep infinity
    # network_mode: service:db

  db: # 3306
    image: mariadb:10.7
    restart: unless-stopped
    # volumes: 
    #   - mariadb-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  mailhog: # 1025 - SMTP, 8025 - HTTP
    image: mailhog/mailhog
    restart: unless-stopped
    # Add "forwardPorts": ["1025", "8025"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

# TODO: recover volumes 
# volumes:
#   mariadb-data: